import React from 'react';

function Habilidades() {
  return (
    <section>
      <h2 className="title">Habilidades</h2>
      <article>
        <h4>Programación</h4>
        <ul>
          <li>
            <img
              align="left"
              alt="HTML5"
              width="30px"
              src="https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/html/html.png"
            />
          </li>
          <li>
            <img
              align="left"
              alt="CSS3"
              width="30px"
              src="https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/css/css.png"
            />
          </li>
          <li>
            <img
              align="left"
              alt="JavaScript"
              width="30px"
              src="https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/javascript/javascript.png"
            />
          </li>
          <li>
            <img
              align="left"
              src="https://raw.githubusercontent.com/devicons/devicon/master/icons/react/react-original-wordmark.svg"
              alt="react"
              width="30"
              height="30"
            />
          </li>
          <li>
            <img
              align="left"
              alt="Gulp"
              width="30px"
              src="https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/gulp/gulp.png"
            />
          </li>
          <li>
            <img
              align="left"
              alt="Git"
              width="30px"
              src="https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/git/git.png"
            />
          </li>
          <li>
            <img
              align="left"
              alt="Node.js"
              width="30px"
              src="https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/nodejs/nodejs.png"
            />
          </li>
          <li>
            <img
              align="left"
              alt="Bootstrap"
              width="30px"
              src="https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/bootstrap/bootstrap.png"
            />
          </li>
          <li>
            <img
              align="left"
              alt="Sass"
              width="30px"
              src="https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/sass/sass.png"
            />
          </li>
          <li>
            <img
              align="left"
              src="https://raw.githubusercontent.com/devicons/devicon/master/icons/nodejs/nodejs-original-wordmark.svg"
              alt="nodejs"
              width="40"
              height="40"
            />
          </li>
        </ul>
      </article>
      <article>
        <h4>Diseño Gráfico</h4>
        <ul>
          <li>
            <img
              align="left"
              alt="AutoCad"
              width="50px"
              src="https://1000marcas.net/wp-content/uploads/2020/01/AutoCAD-Logo.png"
            />
          </li>
          <li>
            <img
              align="left"
              alt="Indesign"
              width="35px"
              src="https://thinkvox.com.mx/wp-content/uploads/2020/08/Logo-adobe-indesign.png"
            />
          </li>
          <li>
            <img
              align="left"
              alt="Illustrator"
              width="27px"
              src="https://cdn.worldvectorlogo.com/logos/adobe-illustrator-cc-2019.svg"
            />
          </li>
          <li>
            <img
              align="left"
              alt="Photoshop"
              width="65px"
              src="https://www.solvetic.com/uploads/monthly_04_2016/tutorials-9832-0-29308300-1461599966.png"
            />
          </li>
          <li>
            <img
              align="left"
              src="https://www.vectorlogo.zone/logos/sketchapp/sketchapp-icon.svg"
              alt="sketch"
              width="30"
            />
          </li>
          <li>
            <img
              align="left"
              src="https://cdn.worldvectorlogo.com/logos/adobe-xd.svg"
              alt="xd"
              width="25"
            />
          </li>
        </ul>
      </article>
      <article>
        <h3>Herramientas</h3>
        <ul>
          <li>
            <img
              align="left"
              alt="Github"
              width="30px"
              src="https://image.flaticon.com/icons/png/512/25/25231.png"
            />
          </li>
          <li>
            <img
              align="left"
              alt="Npm"
              width="30px"
              src="https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/npm/npm.png"
            />
          </li>
          <li>
            <img
              align="left"
              alt="Visual Studio Code"
              width="30px"
              src="https://upload.wikimedia.org/wikipedia/commons/thumb/9/9a/Visual_Studio_Code_1.35_icon.svg/1024px-Visual_Studio_Code_1.35_icon.svg.png"
            />
          </li>
          <li>
            <img
              align="left"
              alt="Zeplin"
              width="30px"
              src="https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/zeplin/zeplin.png"
            />
          </li>
          <li>
            <img
              align="left"
              alt="Trello"
              width="35px"
              src="https://img.icons8.com/color/452/trello.png"
            />
          </li>
          <li>
            <img
              align="left"
              alt="Slack"
              width="30px"
              src="https://img.icons8.com/color/452/slack-new.png"
            />
          </li>
        </ul>
      </article>
    </section>
  );
}
export default Habilidades;
